/* The following code was generated by JFlex 1.4.3 on 9/10/18 7:13 PM */

//package statements
//import statements
package services;
import Beans.Token;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 9/10/18 7:13 PM from the specification file
 * <tt>/home/rajatds/workspace/CoolCompiler/src/services/lexerSpec.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\0\1\42"+
    "\5\0\1\45\1\46\1\55\1\54\1\51\1\4\1\61\1\56\12\10"+
    "\1\53\1\47\1\52\1\60\1\62\1\0\1\50\4\5\1\27\1\31"+
    "\5\5\1\30\3\5\1\35\2\5\1\26\1\33\4\5\1\34\1\5"+
    "\1\6\1\63\2\6\1\32\1\57\1\15\1\7\1\14\1\41\1\17"+
    "\1\25\1\7\1\22\1\20\2\7\1\11\1\7\1\21\1\12\1\13"+
    "\1\7\1\23\1\16\1\24\1\37\1\40\1\36\3\7\1\43\1\0"+
    "\1\44\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\5\1\6\12\5"+
    "\1\4\1\5\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\2\2\5\1\32"+
    "\7\5\1\33\1\34\5\5\1\35\1\4\1\5\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\5\1\45"+
    "\10\5\1\46\1\47\3\5\1\4\1\5\1\50\1\51"+
    "\1\5\1\52\1\53\1\54\1\55\2\5\1\56\1\57"+
    "\1\5\1\4\1\5\1\60\2\5\1\61\1\4\1\62"+
    "\1\63\1\5\1\4\1\5\1\4\1\64\1\4\1\65";

  private static int [] zzUnpackAction() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\150\0\320\0\u0104\0\u0138"+
    "\0\u016c\0\u01a0\0\u01d4\0\u0208\0\u023c\0\u0270\0\u02a4\0\u02d8"+
    "\0\u030c\0\u0340\0\u0374\0\u03a8\0\u03dc\0\150\0\150\0\150"+
    "\0\150\0\150\0\150\0\150\0\150\0\u0410\0\150\0\150"+
    "\0\150\0\150\0\150\0\u0444\0\150\0\u0478\0\150\0\u04ac"+
    "\0\u04e0\0\u0514\0\u0548\0\u0138\0\u057c\0\u05b0\0\u05e4\0\u0618"+
    "\0\u064c\0\u0680\0\u06b4\0\u06e8\0\u0138\0\u071c\0\u0750\0\u0784"+
    "\0\u07b8\0\u07ec\0\u0138\0\u0820\0\u0854\0\150\0\150\0\150"+
    "\0\150\0\150\0\150\0\150\0\u0888\0\u0138\0\u08bc\0\u08f0"+
    "\0\u0924\0\u0958\0\u098c\0\u09c0\0\u09f4\0\u0a28\0\u0138\0\u0138"+
    "\0\u0a5c\0\u0a90\0\u0ac4\0\u0af8\0\u0b2c\0\u0138\0\u0138\0\u0b60"+
    "\0\u0138\0\u0138\0\u0138\0\u0138\0\u0b94\0\u0bc8\0\u0138\0\u0138"+
    "\0\u0bfc\0\u0c30\0\u0c64\0\u0138\0\u0c98\0\u0ccc\0\u0138\0\u0d00"+
    "\0\u0138\0\u0138\0\u0d34\0\u0d68\0\u0d9c\0\u0dd0\0\u0138\0\u0e04"+
    "\0\u0104";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\2\5\1\6\1\7\1\3\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\10\1\16\1\17\1\20"+
    "\1\21\2\10\1\22\1\23\1\24\3\7\1\3\3\7"+
    "\1\25\3\10\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\2\3\1\46\1\3\1\0\37\46\1\47"+
    "\20\46\1\50\66\0\1\5\65\0\1\51\64\0\3\7"+
    "\1\0\31\7\15\0\1\7\3\0\1\7\5\0\3\10"+
    "\1\0\31\10\15\0\1\10\3\0\1\10\10\0\1\11"+
    "\60\0\3\10\1\0\1\10\1\52\4\10\1\53\22\10"+
    "\15\0\1\10\3\0\1\10\5\0\3\10\1\0\14\10"+
    "\1\54\14\10\15\0\1\10\3\0\1\10\5\0\3\10"+
    "\1\0\1\10\1\55\27\10\15\0\1\10\3\0\1\10"+
    "\5\0\3\10\1\0\1\56\3\10\1\57\24\10\15\0"+
    "\1\10\3\0\1\10\5\0\3\10\1\0\6\10\1\60"+
    "\22\10\15\0\1\10\3\0\1\10\5\0\3\10\1\0"+
    "\1\61\4\10\1\62\23\10\15\0\1\10\3\0\1\10"+
    "\5\0\3\10\1\0\5\10\1\63\2\10\1\64\3\10"+
    "\1\65\14\10\15\0\1\10\3\0\1\10\5\0\3\10"+
    "\1\0\1\10\1\66\4\10\1\67\22\10\15\0\1\10"+
    "\3\0\1\10\5\0\3\10\1\0\11\10\1\70\1\71"+
    "\16\10\15\0\1\10\3\0\1\10\5\0\3\10\1\0"+
    "\4\10\1\72\2\10\1\73\21\10\15\0\1\10\3\0"+
    "\1\10\5\0\3\7\1\0\16\7\1\74\12\7\15\0"+
    "\1\7\3\0\1\7\5\0\3\10\1\0\11\10\1\75"+
    "\17\10\15\0\1\10\3\0\1\10\4\0\1\76\53\0"+
    "\1\77\65\0\1\100\1\0\1\46\2\0\37\46\1\0"+
    "\20\46\22\0\1\101\1\0\1\102\1\103\15\0\1\104"+
    "\21\0\1\51\1\4\1\5\61\51\5\0\3\10\1\0"+
    "\1\10\1\105\27\10\15\0\1\10\3\0\1\10\5\0"+
    "\3\10\1\0\13\10\1\106\15\10\15\0\1\10\3\0"+
    "\1\10\5\0\3\10\1\0\1\10\1\107\27\10\15\0"+
    "\1\10\3\0\1\10\5\0\3\10\1\0\4\10\1\110"+
    "\24\10\15\0\1\10\3\0\1\10\5\0\3\10\1\0"+
    "\5\10\1\111\23\10\15\0\1\10\3\0\1\10\5\0"+
    "\3\10\1\0\1\112\30\10\15\0\1\10\3\0\1\10"+
    "\5\0\3\10\1\0\5\10\1\113\23\10\15\0\1\10"+
    "\3\0\1\10\5\0\3\10\1\0\4\10\1\114\24\10"+
    "\15\0\1\10\3\0\1\10\5\0\3\10\1\0\27\10"+
    "\1\115\1\10\15\0\1\10\3\0\1\10\5\0\3\10"+
    "\1\0\11\10\1\116\17\10\15\0\1\10\3\0\1\10"+
    "\5\0\3\10\1\0\13\10\1\117\15\10\15\0\1\10"+
    "\3\0\1\10\5\0\3\10\1\0\25\10\1\120\3\10"+
    "\15\0\1\10\3\0\1\10\5\0\3\10\1\0\6\10"+
    "\1\121\22\10\15\0\1\10\3\0\1\10\5\0\3\10"+
    "\1\0\26\10\1\122\2\10\15\0\1\10\3\0\1\10"+
    "\5\0\3\10\1\0\1\123\30\10\15\0\1\10\3\0"+
    "\1\10\5\0\3\7\1\0\17\7\1\124\11\7\15\0"+
    "\1\7\3\0\1\7\5\0\3\10\1\0\7\10\1\125"+
    "\21\10\15\0\1\10\3\0\1\10\5\0\3\10\1\0"+
    "\2\10\1\126\26\10\15\0\1\10\3\0\1\10\5\0"+
    "\3\10\1\0\1\127\30\10\15\0\1\10\3\0\1\10"+
    "\5\0\3\10\1\0\5\10\1\130\23\10\15\0\1\10"+
    "\3\0\1\10\5\0\3\10\1\0\6\10\1\131\22\10"+
    "\15\0\1\10\3\0\1\10\5\0\3\10\1\0\14\10"+
    "\1\132\14\10\15\0\1\10\3\0\1\10\5\0\3\10"+
    "\1\0\6\10\1\133\22\10\15\0\1\10\3\0\1\10"+
    "\5\0\3\10\1\0\3\10\1\134\25\10\15\0\1\10"+
    "\3\0\1\10\5\0\3\10\1\0\1\10\1\135\27\10"+
    "\15\0\1\10\3\0\1\10\5\0\3\10\1\0\6\10"+
    "\1\136\22\10\15\0\1\10\3\0\1\10\5\0\3\10"+
    "\1\0\10\10\1\137\20\10\15\0\1\10\3\0\1\10"+
    "\5\0\3\10\1\0\6\10\1\140\22\10\15\0\1\10"+
    "\3\0\1\10\5\0\3\10\1\0\5\10\1\141\23\10"+
    "\15\0\1\10\3\0\1\10\5\0\3\7\1\0\20\7"+
    "\1\142\10\7\15\0\1\7\3\0\1\7\5\0\3\10"+
    "\1\0\1\143\30\10\15\0\1\10\3\0\1\10\5\0"+
    "\3\10\1\0\5\10\1\144\23\10\15\0\1\10\3\0"+
    "\1\10\5\0\3\10\1\0\7\10\1\145\21\10\15\0"+
    "\1\10\3\0\1\10\5\0\3\10\1\0\12\10\1\146"+
    "\16\10\15\0\1\10\3\0\1\10\5\0\3\10\1\0"+
    "\6\10\1\147\22\10\15\0\1\10\3\0\1\10\5\0"+
    "\3\7\1\0\21\7\1\150\7\7\15\0\1\7\3\0"+
    "\1\7\5\0\3\10\1\0\6\10\1\151\22\10\15\0"+
    "\1\10\3\0\1\10\5\0\3\10\1\0\30\10\1\152"+
    "\15\0\1\10\3\0\1\10\5\0\3\10\1\0\7\10"+
    "\1\153\21\10\15\0\1\10\3\0\1\10\5\0\3\7"+
    "\1\0\22\7\1\154\6\7\15\0\1\7\3\0\1\7"+
    "\5\0\3\10\1\0\13\10\1\155\15\10\15\0\1\10"+
    "\3\0\1\10\5\0\3\7\1\0\23\7\1\156\5\7"+
    "\15\0\1\7\3\0\1\7\5\0\3\10\1\0\5\10"+
    "\1\157\23\10\15\0\1\10\3\0\1\10\5\0\3\7"+
    "\1\0\24\7\1\160\4\7\15\0\1\7\3\0\1\7"+
    "\5\0\3\7\1\0\16\7\1\161\12\7\15\0\1\7"+
    "\3\0\1\7";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3640];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\20\1\10\11\1\1\5\11"+
    "\1\1\1\11\1\1\1\11\26\1\7\11\55\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	private Parser yyparser;
	
	StringBuffer string = new StringBuffer();
	public Lexer(java.io.Reader r, Parser yyparser) {
    	this(r);
    	this.yyparser = yyparser;
  	}
	
	int lexical_error(String error){
    	System.out.println(error);
    	return 0;
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 144) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 2: 
          { /* ignore */
          }
        case 54: break;
        case 42: 
          { return  Parser.KEYWORD_CASE ;
          }
        case 55: break;
        case 41: 
          { return    Parser.KEYWORD_POOL;
          }
        case 56: break;
        case 52: 
          { return    Parser.KEYWORD_INHERITS;
          }
        case 57: break;
        case 1: 
          { lexical_error("Illegal character '" +
      	              yytext() +
		      "' at line "+(yyline+1) + " col " +yycolumn);
          }
        case 58: break;
        case 50: 
          { return    Parser.KEYWORD_WHILE;
          }
        case 59: break;
        case 20: 
          { return    Parser.OP_INT_NOT;
          }
        case 60: break;
        case 5: 
          { yyparser.yylval = new ParserVal(yytext()); return Parser.ID;
          }
        case 61: break;
        case 35: 
          { string.append('\t');
          }
        case 62: break;
        case 17: 
          { return    Parser.OP_ADD;
          }
        case 63: break;
        case 7: 
          { string.setLength(0); yybegin(STRING);
          }
        case 64: break;
        case 53: 
          { return    Parser.KEYWORD_SELFTYPE;
          }
        case 65: break;
        case 28: 
          { return    Parser.KEYWORD_IF;
          }
        case 66: break;
        case 3: 
          { return    Parser.OP_SUB;
          }
        case 67: break;
        case 45: 
          { return    Parser.KEYWORD_ESAC;
          }
        case 68: break;
        case 44: 
          { return  Parser.KEYWORD_ELSE;
          }
        case 69: break;
        case 25: 
          { string.append('\\');
          }
        case 70: break;
        case 38: 
          { return    Parser.KEYWORD_NOT;
          }
        case 71: break;
        case 10: 
          { return  Parser.SYM_LPAREN;
          }
        case 72: break;
        case 34: 
          { string.append('\r');
          }
        case 73: break;
        case 4: 
          { yyparser.yylval = new ParserVal(yytext()); return Parser.TYPE;
          }
        case 74: break;
        case 48: 
          { return  Parser.KEYWORD_CLASS ;
          }
        case 75: break;
        case 6: 
          { yyparser.yylval = new ParserVal(Integer.parseInt(yytext())); return Parser.INTEGER;
          }
        case 76: break;
        case 43: 
          { return    Parser.KEYWORD_SELF;
          }
        case 77: break;
        case 36: 
          { string.append('\"');
          }
        case 78: break;
        case 39: 
          { return    Parser.KEYWORD_NEW;
          }
        case 79: break;
        case 18: 
          { return    Parser.OP_MUL;
          }
        case 80: break;
        case 31: 
          { return    Parser.OP_LESSTHANEQUAL;
          }
        case 81: break;
        case 26: 
          { return    Parser.KEYWORD_OF;
          }
        case 82: break;
        case 29: 
          { return    Parser.KEYWORD_FI;
          }
        case 83: break;
        case 46: 
          { return    Parser.KEYWORD_THEN;
          }
        case 84: break;
        case 27: 
          { return    Parser.KEYWORD_IN;
          }
        case 85: break;
        case 51: 
          { return    Parser.KEYWORD_ISVOID;
          }
        case 86: break;
        case 8: 
          { return  Parser.SYM_LBRACE;
          }
        case 87: break;
        case 9: 
          { return  Parser.SYM_RBRACE;
          }
        case 88: break;
        case 12: 
          { return    Parser.SYM_SEMICOLON;
          }
        case 89: break;
        case 37: 
          { return    Parser.KEYWORD_LET;
          }
        case 90: break;
        case 49: 
          { return    Parser.KEYWORD_FALSE;
          }
        case 91: break;
        case 33: 
          { string.append('\n');
          }
        case 92: break;
        case 11: 
          { return    Parser.SYM_RPAREN;
          }
        case 93: break;
        case 19: 
          { return    Parser.OP_DIVIDE;
          }
        case 94: break;
        case 30: 
          { return    Parser.SYM_ASSIGNMENT;
          }
        case 95: break;
        case 47: 
          { return    Parser.KEYWORD_TRUE;
          }
        case 96: break;
        case 14: 
          { return    Parser.SYM_COMMA;
          }
        case 97: break;
        case 21: 
          { return    Parser.OP_EQUAL;
          }
        case 98: break;
        case 32: 
          { return    Parser.OP_CASE_COMP;
          }
        case 99: break;
        case 24: 
          { yybegin(YYINITIAL); 
      								   yyparser.yylval = new ParserVal(string.toString());
                                       return Parser.STRING_LITERAL;
          }
        case 100: break;
        case 22: 
          { return    Parser.OP_DOT;
          }
        case 101: break;
        case 16: 
          { return    Parser.SYM_COLON;
          }
        case 102: break;
        case 15: 
          { return    Parser.OP_LESSTHAN;
          }
        case 103: break;
        case 13: 
          { return    Parser.SYM_SCOPE_OP;
          }
        case 104: break;
        case 23: 
          { string.append( yytext() );
          }
        case 105: break;
        case 40: 
          { return  Parser.KEYWORD_LOOP ;
          }
        case 106: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return 0; }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
